name: Release Drafter Owner

on:
  push:
    branches:
      - main
    paths:
      - "apps/owner/**"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.calver.outputs.version }}
    steps:
      - name: Generate Calendar Version
        id: calver
        run: echo "version=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_OUTPUT
        env:
          TZ: "Asia/Tokyo"
  owner:
    name: '[owner] Draft release'
    needs: create-version
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348 # v6.0.0
        with:
          config-name: release-drafter-owner.yml
          name: owner_${{ needs.create-version.outputs.version }}_release
          tag: owner_${{ needs.create-version.outputs.version }}_release
