name: Manual Generate Release Tag

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Project name to run'
        required: true
        type: choice
        options:
          - remote
          - client-owner
          - owner
          # Todo: Add other project options

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Calendar Version
        id: calver
        run: echo "version=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_OUTPUT
        env:
          TZ: "Asia/Tokyo"
          
      - name: '[${{ inputs.target }}] Draft release'
        uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348 # v6.0.0
        with:
          config-name: release-drafter-${{ inputs.target }}.yml
          name: ${{ inputs.target }}_${{ steps.calver.outputs.version }}_release
          tag: ${{ inputs.target }}_${{ steps.calver.outputs.version }}_release
